[package]
name = "twitch"
version = "1.0.0"
edition = "2021"

[dependencies]
graphql-parser = "0.4.0"
itertools = "0.12.0"
rand = "0.8.5"
regex = "1.10.2"
serde_json = "1.0.108"
ureq = "2.9.1"
url = "2.5.0"